const Users=require("../models/users.js"),Pins=require("../models/pins.js");function ClickHandler(){// Load user data
// Retrieve all pins in overall collection
// Add pin to user's list and overall collection
// Remove pin from user's list and overall collection
// Like a pin
// Unlike a pin
this.loadUser=function(a,b){Users.findOne({id:a.session.userId},{_id:0,__v:0},(a,c)=>a?b.send("error"):c?b.json(c):b.send("no"))},this.getAllPins=function(a,b){Pins.find({},{_id:0}).exec((a,c)=>a?b.send("error"):b.json(c))},this.addPin=function(a,b,c,d){// First, ensure pin doesn't already exist in user's list
Users.findOne({id:a.userId,pins:b},{_id:0,__v:0},(e,f)=>e?d.send("error"):f?d.send("exists"):Users.updateOne({id:a.userId},{$addToSet:{pins:b}}).exec(e=>{if(e)return d.send("error");// Add pin to overall collection
const f=new Pins({caption:c,url:b,ownerId:a.userId,ownerName:a.userName});return f.save().then(d.json({ownerId:a.userId,ownerName:a.userName}))}))},this.delPin=function(a,b,c){Users.findOneAndUpdate({id:a.userId},{$pull:{pins:b}},{projection:{_id:0,__v:0,"incomingRequests._id":0,"outgoingRequests._id":0},new:!0}).exec((d,e)=>d?c.send("error"):e?Pins.remove({url:b,ownerId:a.userId}).exec(b=>b?c.send("error"):c.send(a.userId)):c.send("no"))},this.likePin=function(a,b,c){const d=JSON.parse(b);// First, ensure user doesn't already like the pin
d.url=decodeURIComponent(d.url),Users.findOne({id:a,"likes.url":d.url,"likes.ownerId":d.owner},{_id:0,__v:0},(b,e)=>b?c.send("error"):e?c.send("exists"):Pins.findOneAndUpdate({url:d.url,ownerId:d.owner},{$inc:{likes:1}})// Then, update the requester's list of liked pins
.exec(b=>b?c.send("error"):Users.findOneAndUpdate({id:a},{$addToSet:{likes:{url:d.url,ownerId:d.owner}}},{projection:{_id:0,__v:0,"likes._id":0},new:!0}).exec((a,b)=>{a&&c.send("error"),c.json(b)})))},this.unlikePin=function(a,b,c){const d=JSON.parse(b);// First, remove like from the requester's list
d.url=decodeURIComponent(d.url),Users.findOneAndUpdate({id:a},{$pull:{likes:{url:d.url,ownerId:d.owner}}},{projection:{_id:0,__v:0,"likes._id":0},new:!0}).exec((a,b)=>a?c.send("error"):b?Pins.findOneAndUpdate({url:d.url,ownerId:d.owner},{$inc:{likes:-1}}).exec((a,b)=>{a&&c.send("error"),c.json(b)}):c.send("no"))}}module.exports=ClickHandler;