$(document).ready(()=>{// Automatically load and display all pins
// When navbar title is clicked, show all pins and shuffle
// Activate pin-filter menu buttons
ajaxFunctions.ready(ajaxFunctions.ajaxRequest("GET","/api/allPins/",showAllPins)),$(".brand-logo").click(()=>{filterPinsByLink("*"),$(".pins").isotope("shuffle")}),$(".filter-btn").click(function(){filterPinsByBtn(this)})});// Display pin in big-image modal
function bigImg(a){$("#bigImg").attr("src",a.attr("src")),$("#bigImgCaption").html(a.attr("alt")),$("#bigImgOwner").html(`Pinned by ${a.attr("data-owner-name")}`),$(".modal-big-img").modal("open")}// Show an error message
function errorMsg(a="An error has occurred. Please try again later.",b){b&&$(b).css("pointer-events","unset"),Materialize.toast(a,3e3,"error")}// Show/hide progress bar, which can be determinate or indeterminate
function progress(a,b){"show"===a?(b&&$(".bar").removeClass("determinate").addClass("indeterminate"),$(".progress").removeClass("hidden")):($(".progress").addClass("hidden"),b&&$(".bar").removeClass("indeterminate").addClass("determinate"))}// Display all pins as Isotope elements
function showAllPins(a){progress("show");const b=JSON.parse(a);let c=0,d=0;b.forEach((a,e)=>{// When at the end of the list (all pin HTML generated), update UI
if($(".pins").append(generatePin(a.url,a.caption,a.ownerId,a.ownerName,a.likes)),e===b.length-1){$("#loading").fadeOut().remove();// Initialize Isotope grid
const a=$(".pins").isotope({itemSelector:".grid-item",masonry:{isFitWidth:!0}});// Update progress bar and Isotope layout after each image loads
a.imagesLoaded().progress(()=>{var e=Math.round;c++,d=e(100*(c/b.length)),$(".determinate").css("width",`${d}%`),a.isotope("layout")}),$(".tooltipped").tooltip(),$(".modal-big-img").modal(),$(".grid-item img").click(function(){bigImg($(this))}),$(".grid-item .left a").click(function(){filterPinsByLink(`[data-owner="${$(this).data("owner")}"]`)}),checkLoginStatus(),a.imagesLoaded(()=>{progress("hide"),$(".grid-item img").css("background-image","none")})}})}